version: '3.1'

services:

  db:
    image: mysql:5.7
    container_name: database_jpa
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookstore-jpa
    ports:
      - "3306:3306"